// <auto-generated />
using System;
using MagicVilla_APi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_APi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_APi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("area")
                        .HasColumnType("float");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numOFrooms")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("villaNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luxury beachfront villa with stunning ocean views",
                            OwnerName = "Emily Johnson",
                            StreetName = "Ocean Drive",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 500.25,
                            city = "Miami",
                            imageUrl = "https://example.com/villa1-image.jpg",
                            numOFrooms = 6,
                            price = 2500000.0,
                            villaNum = 5678
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern villa with a rooftop terrace and panoramic city views",
                            OwnerName = "Michael Anderson",
                            StreetName = "Park Avenue",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 280.5,
                            city = "New York",
                            imageUrl = "https://example.com/villa2-image.jpg",
                            numOFrooms = 4,
                            price = 1800000.0,
                            villaNum = 2468
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant villa surrounded by lush green gardens",
                            OwnerName = "Sophia Lee",
                            StreetName = "Kensington High Street",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 400.75,
                            city = "London",
                            imageUrl = "https://example.com/villa3-image.jpg",
                            numOFrooms = 7,
                            price = 2200000.0,
                            villaNum = 1357
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mediterranean-style villa with a private courtyard and fountain",
                            OwnerName = "Benjamin Martinez",
                            StreetName = "Passeig de Gràcia",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 320.0,
                            city = "Barcelona",
                            imageUrl = "https://example.com/villa4-image.jpg",
                            numOFrooms = 5,
                            price = 1950000.0,
                            villaNum = 9876
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rustic countryside villa with panoramic mountain views",
                            OwnerName = "Olivia Wilson",
                            StreetName = "Rue du Rhône",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 600.79999999999995,
                            city = "Geneva",
                            imageUrl = "https://example.com/villa5-image.jpg",
                            numOFrooms = 8,
                            price = 3400000.0,
                            villaNum = 3691
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contemporary villa with a private infinity pool overlooking the ocean",
                            OwnerName = "Daniel Thompson",
                            StreetName = "Bondi Road",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            area = 450.30000000000001,
                            city = "Sydney",
                            imageUrl = "https://example.com/villa6-image.jpg",
                            numOFrooms = 6,
                            price = 2700000.0,
                            villaNum = 8023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
